# Generated by Django 3.2.22 on 2024-01-04 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bucket_list',
            field=models.TextField(blank=True, help_text="User's travel bucket list.", null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='reward_points',
            field=models.IntegerField(default=0, help_text='Reward points for the user.'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='travel_trips',
            field=models.PositiveIntegerField(default=0, help_text='Number of travel trips taken by the user.'),
        ),
    ]
