# Generated by Django 3.2.22 on 2024-01-18 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20240104_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='about_you',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='my_images',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='my_interest',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='my_status_images',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
