# Generated by Django 3.2.22 on 2024-01-18 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20240118_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bucket_list',
            field=models.PositiveIntegerField(default=0, help_text="User's travel bucket list."),
        ),
    ]
