# Generated by Django 3.2.22 on 2024-01-18 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_bucket_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='business_images/')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ManyToManyField(blank=True, to='accounts.Image'),
        ),
    ]
