# Generated by Django 3.2.22 on 2024-01-18 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20240118_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='userImages/')),
            ],
        ),
        migrations.CreateModel(
            name='MyStatusImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='userImages/')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='userImages/')),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='my_images',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='my_status_images',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='profile_image',
        ),
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='userImages/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='my_images',
            field=models.ManyToManyField(blank=True, to='accounts.MyImages'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='my_status_images',
            field=models.ManyToManyField(blank=True, to='accounts.MyStatusImages'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ManyToManyField(blank=True, to='accounts.ProfileImage'),
        ),
    ]
