# Generated by Django 3.2.22 on 2024-01-18 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20240118_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='image',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
