# Generated by Django 3.2.22 on 2024-01-18 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20240118_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileimage',
            name='number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='my_images',
            field=models.ManyToManyField(blank=True, related_name='my_images', to='accounts.MyImages'),
        ),
    ]
