# Generated by Django 3.2.22 on 2024-01-18 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20240118_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileimage',
            name='number',
        ),
        migrations.AddField(
            model_name='myimages',
            name='userName',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='mystatusimages',
            name='userName',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
