# Generated by Django 3.2.22 on 2024-01-21 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_customuser_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileimage',
            name='userName',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
