# Generated by Django 3.2.22 on 2024-02-01 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_profileimage_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='bucket_list',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='my_interest',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='reward_points',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='travel_trips',
        ),
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='favorites',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='forum_posts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='interest1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='interest2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='interest3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='interest4',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='interest5',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='photos_added',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
