# Generated by Django 3.2.22 on 2024-02-08 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_customuser_profile_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileImage',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='lname',
        ),
        migrations.AddField(
            model_name='customuser',
            name='nameUser',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
